name: Catgirl Edition Compiled

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Package
    runs-on: self-hosted
    container:
      image: archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and create build user
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git zip bc cpio pahole python clang llvm lld
          useradd -m builduser
          echo "builduser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Fix workspace permissions
        run: |
          chown -R builduser:builduser "$GITHUB_WORKSPACE"

      - name: Build linux-catgirl-edition via makepkg
        run: | # The sed command is for turning on CI mode
          sudo -u builduser bash <<'EOF'
            cd "$GITHUB_WORKSPACE"
            sed -i 's|: "${_localmodcfg:=yes}"|: "${_localmodcfg:=no}"|' PKGBUILD
            sed -i 's|: "${_processor_opt:=}"|: "${_processor_opt:=GENERIC_V3}"|' PKGBUILD
            sed -i 's|: "${_use_auto_optimization:=yes}"|: "${_use_auto_optimization:=no}"|' PKGBUILD
            sed -i 's|: "${_unattended_make_prepare:=no}"|: "${_unattended_make_prepare:=yes}"|' PKGBUILD
            sed -i 's|: "${_makenconfig:=yes}"|: "${_makenconfig:=no}"|' PKGBUILD
            sed -i 's|: "${_no_32bit:=yes}"|: "${_no_32bit:=no}"|' PKGBUILD
            sed -i 's|: "${_no_compressed_initramfs:=yes}"|: "${_no_compressed_initramfs:=no}"|' PKGBUILD
            makepkg -scf --cleanbuild --skipchecksums
          EOF

      - name: .zip the linux-catgirl-edition directory
        run: |
          zip -r linux-catgirl-edition.zip . -x ".git/*" ".github/*" "README.md" "linux-[0-9]*.tar.xz"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-catgirl-edition-compiled
          path: linux-catgirl-edition.zip
